{
    'name': 'Firmadas',
    'version': '1.0',
    'summary': 'Gestión de oportunidades firmadas',
    'author': 'Ricardo Alfaro',
    'category': 'CRM',
    'depends': ['crm', 'sale', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'security/service_manager_group.xml',
        'views/crm_lead_view.xml',
        'views/firmadas_menu.xml',
        'views/res_partner_view.xml',
        'views/res_partner_interviniente_views.xml',
        'views/interviniente_action.xml',
        'views/interviniente_menu.xml',
        'data/default_product.xml',
        'data/default_producto_tipo.xml',
        'data/default_producto_subtipo.xml',
        'data/default_producto_estatus1.xml',
        'data/default_producto_estatus2.xml',
        'data/default_producto_estatus3.xml',
        'data/default_producto_estatus4.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'external_dependencies': {'python': []},
}